---
name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  Build:
    name: Flipper Zero toolchain

    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’¾ Check out repository
        uses: actions/checkout@v3

      - name: ğŸ› ï¸ Set up toolchain and build firmware
        run: ./fbt

      - name: ğŸ’­ Determine firmware API version
        run: |
          echo "FZ_API_VERSION=$(grep '^Version,' firmware/targets/f7/api_symbols.csv | cut -d, -f3)" >> "${GITHUB_ENV}"

      - name: ğŸ¬ Build applications
        run: ./fbt fap_dist

      - name: ğŸ“¦ Package apps as artifact
        uses: actions/upload-artifact@v3
        with:
          name: apps-api-${{ env.FZ_API_VERSION }}
          path: build/f7-firmware-D/.extapps/*.fap

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
